name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      # since this is a mono-repo, we specify the path where container is,
      # in order to run actions only when something changes inside container folder
      - 'packages/container/**'

# set our execution environment in an specific directory
# when we run for example, npm install, it will run inside our working-directory
defaults:
  run: 
    working-directory: packages/container

# We can have several jobs and they will run in parallel by default, but in this case, we will use only one.
jobs:
  build:
    runs-on: ubuntu-latest # this virtual machine is created by github

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build # generate the dist folder we want to upload in AWS-S3

      # the one bellow is to get access to the AWS-CLI
      - uses: shinyinc/action-aws-cli@v1.2
      # upload the dist folder to the bucket we created on S3
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} # Get the region when you create the bucket